webshop/webshop/Pages/Admin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.Sqlite;
using System.ComponentModel.DataAnnotations;

namespace webshop.Pages
{
    public class AdminModel : PageModel
    {
        private readonly string connectionString = "Data Source=webshop.db";

        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (string.IsNullOrEmpty(Username) || string.IsNullOrEmpty(Password))
            {
                ModelState.AddModelError(string.Empty, "Gebruikersnaam en wachtwoord zijn verplicht!");
                return Page();
            }

            using (var connection = new SqliteConnection(connectionString))
            {
                connection.Open();

                var selectCommand = connection.CreateCommand();
                selectCommand.CommandText = $"SELECT * FROM admin WHERE username = @username AND password = @password";
                selectCommand.Parameters.AddWithValue("@username", Username);
                selectCommand.Parameters.AddWithValue("@password", Password);

                var reader = selectCommand.ExecuteReader();

                if (reader.Read())
                {
                    HttpContext.Session.SetString("Username", Username);
                    return RedirectToPage("/Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Gebruikersnaam of wachtwoord is onjuist.");
                    return Page();
                }
            }
        }
    }
}

webshop/webshop/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using Microsoft.Data.Sqlite;
using Microsoft.AspNetCore.Http;

namespace webshop.Pages
{
    public class CartModel : PageModel
    {
        private readonly string _dbPath = "webshop.db";

        public List<CartItem> CartItems { get; set; }

        public class CartItem
        {
            public string ID { get; set; }
            
            public int Prijs { get; set; }

            public string Naam { get; set; }

            public int Quantity { get; set; }
        }

        public void OnGet()
        {
            //haalt data uit de shoppingcart session
            Dictionary<string, int> shoppingCart = HttpContext.Session.Get<Dictionary<string, int>>("ShoppingCart") ?? new Dictionary<string, int>();

            CartItems = new List<CartItem>();

            foreach (var item in shoppingCart)
            {
                string productId = item.Key;
                int quantity = item.Value;

                using (var connection = new SqliteConnection($"Data Source={_dbPath}"))
                {
                    connection.Open();

                    var insertCommand = connection.CreateCommand();
                    insertCommand.CommandText = "SELECT * FROM product WHERE id = @productId";
                    insertCommand.Parameters.AddWithValue("@productId", productId);
                    
                    var reader = insertCommand.ExecuteReader();

                    if (reader.Read())
                    {
                        CartItems.Add(new CartItem
                        {
                            ID = reader.GetInt32(0).ToString(),
                            Naam = reader.GetString(1),
                            Prijs = reader.GetInt32(2),
                            Quantity = quantity
                        });

                    }

                    connection.Close();

                }
            }            
            
        }
        public IActionResult OnPostEmptyCart()
        {
            HttpContext.Session.Remove("ShoppingCart");
            return RedirectToPage("/Cart");
        }
    }
}

webshop/webshop/Pages/DeleteU.cshtml.cs
using System;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.Sqlite;

namespace webshop.Pages
{
    public class DeleteUModel : PageModel
    {
        private readonly string _dbPath = "webshop.db";

        public string Naam { get; set; }

        public async Task<IActionResult> OnGetAsync(string naam)
        {
            Naam = naam;
            
            string username = HttpContext.Session.GetString("Username");
            if (string.IsNullOrEmpty(username))
            {
                // Redirect to login page if the user is not logged in
                return RedirectToPage("Index");
            }

            using (var connection = new SqliteConnection($"Data Source={_dbPath}"))
            {
                connection.Open();

                var deleteCommand = connection.CreateCommand();
                deleteCommand.CommandText = "DELETE FROM product_type WHERE naam = @Naam";
                deleteCommand.Parameters.AddWithValue("@Naam", Naam);
                deleteCommand.ExecuteNonQuery();
            }

            return RedirectToPage("/Upload");
        }
    }
}

webshop/webshop/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.Sqlite;
using System.Text.Json;

namespace webshop.Pages
{
    public class IndexModel : PageModel
    {
        private readonly string _dbPath = "webshop.db";
        private readonly string _uploadFolderPath;

        public List<ProductModel> Producten { get; set; }

        public List<TypeModel> Type { get; set; }

        [BindProperty]
        public string Filter { get; set; }

        public string[] PT_naam;

        public IndexModel(IWebHostEnvironment webHostEnvironment)
        {
            _uploadFolderPath = Path.Combine(webHostEnvironment.WebRootPath, "uploads");
        }

        [Authorize]
        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }

        public IActionResult OnGet( string filterOption)
        {
            using (var connection = new SqliteConnection($"Data Source={_dbPath}"))
            {
                connection.Open();

                var selectCommand = connection.CreateCommand();
                selectCommand.CommandText = "SELECT * FROM product_type";

                var kaas = new List<string>();
                using (var reader = selectCommand.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        kaas.Add(reader.GetString(0));
                    }
                }
                this.PT_naam = kaas.ToArray();

                var types = new List<TypeModel>();

                using (var reader = selectCommand.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        var product_type = new TypeModel()
                        {
                            naam = reader.GetString(0)
                        };

                        types.Add(product_type);
                    }

                }

                Type = types;
            }

            using (var connection = new SqliteConnection($"Data Source={_dbPath}"))
            {
                connection.Open();

                var selectCommand = connection.CreateCommand();
                selectCommand.CommandText = "SELECT * FROM product";

                var producten = new List<ProductModel>();

                using (var reader = selectCommand.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        var product = new ProductModel()
                        {
                            ID = reader.GetString(0),
                            PT_naam = reader.GetString(1),
                            prijs = reader.GetString(2),
                            img = reader.GetString(3),                            
                            naam = reader.GetString(4),
                            FilePath = reader.GetString(5)
                        };

                        producten.Add(product);
                    }
                }

                Producten = producten;
            }

            

            return Page();
        }

        public RedirectToPageResult OnPostAddToCart(string id)
        {
            //Haalt de data uit de shopping cart session
            Dictionary<string, int> shoppingCart = HttpContext.Session.Get<Dictionary<string, int>>("ShoppingCart") ?? new Dictionary<string, int>();
            if (shoppingCart.ContainsKey(id))
            {
                shoppingCart[id] += 1;
            }
            else
            {
                shoppingCart[id] = 1;
            }

            // Slaat de dingetje op :)
            HttpContext.Session.Set("ShoppingCart", shoppingCart);

            return RedirectToPage("Index");
        }
    }

    public static class SessionExtensions
    {
        public static void Set<T>(this ISession session, string key, T value)
        {
            session.SetString(key, JsonSerializer.Serialize(value));
        }

        public static T Get<T>(this ISession session, string key)
        {
            var value = session.GetString(key);
            return value == null ? default(T) : JsonSerializer.Deserialize<T>(value);
        }
    }


    public class ProductModel 
    {
        public string ID { get; set; }
        public string PT_naam { get; set; }
        public string prijs { get; set; }
        public string img { get; set; }        
        public string naam { get; set; }
        public string FilePath { get; set; }
    }

    public class TypeModel
    {
        public string naam { get; set; }
    }
}

webshop/webshop/Pages/upload.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.Sqlite;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Globalization;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace webshop.Pages
{
    public class uploadModel : PageModel
    {
        private readonly string _dbPath = "webshop.db";
        private readonly string _uploadFolderPath;

        [BindProperty]
        [Required(ErrorMessage = "Fill in the fields!")]
        public string PT_naam { get; set; }

        [BindProperty]
        [Required(ErrorMessage = "Fill in the fields!")]
        public int Prijs { get; set; }

        [BindProperty]
        public IFormFileCollection UploadedFiles { get; set; }

        [BindProperty]
        [Required(ErrorMessage = "Fill in the fields!")]
        public string Naam { get; set; }

        public string ErrorMessage { get; set; }

        public string[] PT_name;

        [BindProperty]
        [Required(ErrorMessage = "Fill in a poduct type!")]
        public string ProductType { get; set; }
        
        public List<TypeModel> Types { get; set; }

        [BindProperty]
        public string Type { get; set; }

        [BindProperty]
        public string TypeHidden { get; set; }

        public uploadModel(IWebHostEnvironment webHostEnvironment)
        {
            _uploadFolderPath = Path.Combine(webHostEnvironment.WebRootPath, "uploads");
        }

        public IActionResult OnPostUpdate()
        {

            using (var connection = new SqliteConnection($"Data Source={_dbPath}"))
            {
                connection.Open();

                var updateCommand = connection.CreateCommand();
                updateCommand.CommandText = "UPDATE product_type SET naam = @NaamT WHERE naam = @Naam";
                updateCommand.Parameters.AddWithValue("@NaamT", Type);
                updateCommand.Parameters.AddWithValue("@Naam", TypeHidden);
                updateCommand.ExecuteNonQuery();

            }
            return RedirectToPage("/Upload");
        }

        public IActionResult OnGet()
        {
            string username = HttpContext.Session.GetString("Username");
            if (string.IsNullOrEmpty(username))
            {
                // Redirect to login page if the user is not logged in
                return RedirectToPage("/Index");
            }

            using (var connection = new SqliteConnection($"Data Source={_dbPath}"))
            {
                connection.Open();

                var selectCommand = connection.CreateCommand();
                selectCommand.CommandText = "SELECT * FROM product_type";
                var kaas = new List<string>();
                using (var reader = selectCommand.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        kaas.Add(reader.GetString(0));
                    }
                }
                this.PT_name = kaas.ToArray();

                var types = new List<TypeModel>();

                using (var reader = selectCommand.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        var type = new TypeModel
                        {
                            ProductT = reader.GetString(0)
                        };
                        types.Add(type);
                    }
                }

                Types = types;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostForm1()
        {
            string username = HttpContext.Session.GetString("Username");
            if (string.IsNullOrEmpty(username))
            {
                // Redirect to login page if the user is not logged in
                return RedirectToPage("/Index");
            }

            if (UploadedFiles != null && UploadedFiles.Count > 0)
            {
                try
                {
                    using (var connection = new SqliteConnection($"Data Source={_dbPath}"))
                    {
                        connection.Open();

                        foreach (var file in UploadedFiles)
                        {
                            string fileName = $"{Guid.NewGuid()}{Path.GetExtension(file.FileName)}";

                            string filePath = Path.Combine("uploads", fileName);
                            string physicalPath = Path.Combine(_uploadFolderPath, fileName);

                            using (var fileStream = new FileStream(physicalPath, FileMode.Create))
                            {
                                await file.CopyToAsync(fileStream);
                            }

                            var insertCommand = connection.CreateCommand();
                            insertCommand.CommandText = "INSERT INTO product (PT_naam, prijs, img, naam, FilePath) VALUES ( @PT_naam, @Prijs, @Img, @Naam, @FilePath)";
                            insertCommand.Parameters.AddWithValue("@PT_naam", PT_naam);
                            insertCommand.Parameters.AddWithValue("@Prijs", Prijs);
                            insertCommand.Parameters.AddWithValue("@Img", file.FileName);
                            insertCommand.Parameters.AddWithValue("@Naam", Naam);
                            insertCommand.Parameters.AddWithValue("@FilePath", filePath);
                            insertCommand.ExecuteNonQuery();
                        }
                    }
                }
                catch (Exception ex)
                {
                    ErrorMessage = $"An error occurred while uploading files: {ex.Message}";
                    return Page();
                }
          }

            return RedirectToPage("Index");
        }

        public IActionResult OnPostForm2()
        {
            string username = HttpContext.Session.GetString("Username");
            if (string.IsNullOrEmpty(username))
            {
                // Redirect to login page if the user is not logged in
                return RedirectToPage("/Index");
            }

            if (!string.IsNullOrEmpty(ProductType))
            {
                try
                {
                    using (var connection = new SqliteConnection($"Data Source={_dbPath}"))
                    {
                        connection.Open();

                        var insertCommand = connection.CreateCommand();
                        insertCommand.CommandText = "INSERT INTO product_type (naam) VALUES (@Naam)";
                        insertCommand.Parameters.AddWithValue("@Naam", ProductType);
                        insertCommand.ExecuteNonQuery();
                    }
                }
                catch (Exception ex)
                {
                    ErrorMessage = $"An error occurred while submitting form: {ex.Message}";
                    return Page();
                }
            }

            return RedirectToPage("/Upload");
        }

        public class Form1Model : PageModel
        {
            [BindProperty]
            public string PT_naam { get; set; }

            [BindProperty]
            public int Prijs { get; set; }

            [BindProperty]
            public IFormFileCollection UploadedFiles { get; set; }

            [BindProperty]
            public string Naam { get; set; }

            public string ErrorMessage { get; set; }

            public string[] PT_name;
        }

        public class Form2Model : PageModel
        {
            [BindProperty]
            public string ProductType { get; set;}
        }

        public class TypeModel
        {
            public string ProductT { get; set;}
        }
    }
}

webshop/webshop/Pages/Admin.cshtml
@page
@model webshop.Pages.AdminModel

@using Microsoft.AspNetCore.Mvc.ViewFeatures;
@inject IModelExpressionProvider ModelExpressionProvider

<style>
    /* CSS styles for the form */
    form {
        max-width: 300px;
        margin: 0 auto;
        padding: 20px;
        background-color: #f4f4f4;
        border-radius: 5px;
    }

    label {
        display: block;
        margin-bottom: 10px;
    }

    .input[type="text"],
    .input[type="password"] {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-bottom: 10px;
    }

    button[type="submit"] {
        background-color: #8AFFFF;
        color: black;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        button[type="submit"]:hover {
            background-color: #00FFFF;
        }
</style>

<div class="main">
    <form method="post">
        <div>
            <label for="username" class="">username:</label>
            <input class="input" type="text" id="username" asp-for="Username"/>
        </div>
        <div>
            <label for="password" class="">password:</label>
            <input class="input" type="password" id="password" asp-for="Password" />
        </div>
        <button type="submit" class="">Login</button>
    </form>
</div>

webshop/webshop/Pages/Cart.cshtml
@page
@model webshop.Pages.CartModel
@{
    ViewData["Title"] = "Cart";
}

<h2>Uw winkelwagen</h2>
 

@if (Model.CartItems.Count == 0)
{
    <p>U heeft geen producten in uw winkel karretje!</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Product</th>
                <th>Prijs</th>
                <th>Aantal</th>
                <th>Subtototaal</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.CartItems)
            {
                <tr>
                    <td>@item.Naam</td>
                    <td>€@item.Prijs.ToString()</td>
                    <td>@item.Quantity</td>
                    <td>€@(item.Prijs * item.Quantity)</td>
                </tr>
            }

        </tbody>
    </table>

    <div class="text-right">
        <h4>Totaal aantal producten: @Model.CartItems.Sum(x => x.Quantity).ToString()</h4>
    </div>

    <div class="text-right">
        <h4>Totaal: €@Model.CartItems.Sum(x => x.Prijs * x.Quantity).ToString()</h4>
    </div> 

    <style>
        .btn:hover {
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
        } 

        .btn-clear {
            color: #007bff;
            background-color: transparent;
            border-color: #007bff;
        }

 
        .btn-clear:hover {
            color: #fff;
            background-color: #007bff;
            border-color: #007bff;
        }
    </style> 

    <form method="post" asp-page-handler="EmptyCart">
        <button type="submit" class="btn btn-clear">
            <i class="fas fa-trash"></i> Leeg winkelkarretje
        </button>
        <input type="hidden" name="handler" value="EmptyCart" />
    </form>
    
    <a href="#">
        <button class="btn btn-clear">
            <i class="fas fa-shopping-cart"></i> Bestellen
        </button>
    </a>
}

webshop/webshop/Pages/Delete.cshtml
@page
@model webshop.Pages.DeleteModel
@{
}

webshop/webshop/Pages/DeleteU.cshtml
@page
@model webshop.Pages.DeleteModel
@{
}

webshop/webshop/Pages/Index.cshtml
@page
@model webshop.Pages.IndexModel
@{
    ViewData["Title"] = "Dev Needs";
}

<style>
    .product-container {
        display: flex;
        flex-wrap: wrap;   
        justify-content: center;
    }

    .product-img {
        width: 700px;
        height: auto;
    }

    .container-product {
        display: flex;
        flex-direction: column;
        margin: 20px;
        align-items:center;
    }

    .custom-select {
        appearance: none;
        -webkit-appearance: none;
        -moz-appearance: none;
        padding: 10px 20px;
        font-size: 16px;
        border: none;
        border-radius: 4px;
        background-color: #f2f2f2;
        color: #333;
        cursor: pointer;
    }

        .custom-select:focus {
            outline: none;
            box-shadow: 0 0 0 2px #007bff;
        }

        .custom-select option {
            background-color: #f2f2f2;
            color: #333;
        }

            .custom-select option:checked {
                background-color: #007bff;
                color: #fff;
            }

</style>

<div>

    <img style="width: 100vw; height: 600px; object-fit: cover; margin-right: 5px;" src="media/main.png" />

    <div class="about" id="about">
        <h1>About us</h1>
        <p>
            Hallo en welkom bij onze webshop waar wij producten verkopen voor developers die hun set-up willen upgraden met handige tools.
            Wij houden ons graag bezig met daadwerkelijke tools om bijvoorbeeld je set-up schoon te houden, of een tool voor je telefoon op te laden zonder een oplader te gebruiken etc.
            Het gaat er dus bij ons om dat je fijn en ongehinderd achter een PC kan zitten met volledige focus. Hier onder dus een assortiment met de producten die wij
            verkopen. Bij vragen kunt u verder scrollen en kunt u uw vragen stellen met u contact gegevens.
        </p>
    </div>

    <div class="main" id="producten">
        <div>
            <h2>Products we sell</h2>

            
        </div>
        <div>
            <label>Filter: </label>
            <select id="mySelect" onchange="handleSelectChange()" class="custom-select">
                <option name="Filter" value="">Alles</option>
                @for (var i = 0; i < Model.PT_naam.Length; i++)
                {
                    <option name="Filter" value="@Model.PT_naam[i]">@Model.PT_naam[i]</option>
                }
            </select>
        </div>

        <div class="container">
                

            <div class="product-container">
                @foreach (var product in Model.Producten)
                {
                    <div class="container-product @product.PT_naam">
                        <img class="product-img" src="@product.FilePath">
                        <div>@product.naam</div>
                        <div>@product.prijs</div>

                        @if (!string.IsNullOrEmpty("Username"))
                        {
                            <a href="Delete?product=@product.FilePath&ID=@product.ID" style="color: black; cursor: pointer;">Delete</a>
                        }

                        <form asp-page-handler="AddToCart" method="post">
                            <input type="hidden" name="id" value="@product.ID" />
                            <button type="submit" class="btn btn-outline-primary">
                                <i class="fas fa-cart-plus"></i> Add to Cart
                            </button>
                        </form>
                    </div>
                }
            </div>

            

        </div>
    </div>
</div>

webshop/webshop/Pages/Inlog.cshtml
@page
@model webshop.Pages.InlogModel

@using Microsoft.AspNetCore.Mvc.ViewFeatures;
@inject IModelExpressionProvider ModelExpressionProvider

<style>
    /* CSS styles for the form */
    form {
        max-width: 300px;
        margin: 0 auto;
        padding: 20px;
        background-color: #f4f4f4;
        border-radius: 5px;
    }

    label {
        display: block;
        margin-bottom: 10px;
    }

    .input[type="text"],
    .input[type="password"] {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-bottom: 10px;
    }

    button[type="submit"] {
        background-color: #8AFFFF;
        color: black;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        button[type="submit"]:hover {
            background-color: #00FFFF;
        }

    /* CSS styles for the link */
    .register-link {
        margin-top: 20px;
        text-align: center;
    }

        .register-link a {
            color: #00FFFF;
            text-decoration: none;
        }

            .register-link a:hover {
                text-decoration: underline;
            }
</style>

<div class="main">
    <form method="post">
        <div>
            <label for="username">Username:</label>
            <input class="input" type="text" id="username" asp-for="CustomerName" />
        </div>
        <div>
            <label for="password">Password:</label>
            <input class="input" type="password" id="password" asp-for="Password" />
        </div>
        <button type="submit">Login</button>
    </form>

    <div class="register-link">
        <p>Nog geen account? <a href="Register">Registreer</a></p>
    </div>
</div>

webshop/webshop/Pages/upload.cshtml
@page
@model webshop.Pages.uploadModel
@{
    ViewData["Title"] = "Upload";
}

<style>
    /* CSS styles for the form */
    .form-container {
        max-width: 500px;
        margin: 0 auto;
        padding: 20px;
        background-color: #f4f4f4;
        border-radius: 5px;
    }

        .form-container label {
            display: block;
            margin-bottom: 10px;
        }

        .form-container input[type="text"],
        .form-container input[type="number"],
        .form-container select {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            margin-bottom: 10px;
        }

        .form-container input[type="file"] {
            margin-bottom: 10px;
        }

        .form-container .btn {
            background-color: #8AFFFF;
            color: black;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

            .form-container .btn:hover {
                background-color: #00FFFF;
            }

    /* CSS styles for the table */
    .table-container {
        max-width: 500px;
        margin: 20px auto;
    }

        .table-container table {
            width: 100%;
            border-collapse: collapse;
        }

        .table-container th,
        .table-container td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        .table-container th {
            background-color: #f2f2f2;
        }

        .table-container a {
            color: black;
            cursor: pointer;
            text-decoration: none;
        }

            .table-container a:hover {
                text-decoration: underline;
            }
</style>

<div class="main">
    

    <div class="form-container">
        <h1>Upload product</h1>

        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <div>@Model.ErrorMessage</div>
        }

        <form method="post" enctype="multipart/form-data" asp-page-handler="Form1">
            <div>
                <label for="PT_naam">Type:</label>
                <select asp-for="PT_naam" required>
                    @for (var i = 0; i < Model.PT_name.Length; i++)
                    {
                        <option>@Model.PT_name[i]</option>
                    }
                </select>
            </div>
            <div>
                <label for="prijs">Prijs:</label>
                <input type="number" id="prijs" name="Prijs" asp-for="Prijs" required>
            </div>
            <div>
                <label for="uploadedFiles">Select Photo:</label>
                <input type="file" id="uploadedFiles" name="UploadedFiles" asp-for="UploadedFiles" multiple required>
            </div>
            <div>
                <label for="naam">Naam product:</label>
                <input type="text" id="naam" name="Naam" asp-for="Naam" required>
            </div>
            <div>
                <button type="submit" class="btn">Upload</button>
            </div>
        </form>
    </div>

    <div class="form-container">
        <h1>Add product type</h1>

        <form method="post" asp-page-handler="Form2">
            <div>
                <label for="productType">Product type:</label>
                <input type="text" id="productType" asp-for="ProductType" required>
            </div>
            <button type="submit" class="btn">Submit</button>
        </form>
    </div>

    <div class="table-container">
        <h1>Edit and delete product types</h1>

        <table>
            @foreach (var type in Model.Types)
            {
                <tr>
                    <td><label>@type.ProductT</label></td>
                    <td>
                        <form method="post" asp-page-handler="Update">
                            <div>
                                <input type="text" id="type" asp-for="Type" required>
                                <input type="hidden" value="@type.ProductT" asp-for="TypeHidden">
                                <button type="submit" class="btn">Update</button>
                            </div>
                        </form>
                    </td>
                    <td>
                        <a href="DeleteU?naam=@type.ProductT">Delete</a>
                    </td>
                </tr>
            }
        </table>
    </div>

</div>